config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
root "users#index"

resources :users, only: [:index, :show] do
  resources :posts, only: [:index, :show, :new, :create, :destroy] do
    resources :comments, only: [:create, :new, :destroy] 
    resources :likes, only: [:create, :destroy] 

end
end

# API endpoints

namespace :api do
  namespace :v1 do
    resources :users, only: [:index, :create, :update, :destroy, :show] do
      resources :posts, only: [:index, :create, :update, :destroy, :show] do
        resources :comments, only: [:index, :show, :create]
        resources :likes, only: [:index, :show]
      end
    end
  end
end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :confirmable,
         :recoverable, :rememberable, :validatable
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'
  has_many :posts, foreign_key: 'author_id'

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  ROLES = %i[admin default].freeze

  def is?(requested_role)
    role == requested_role.to_s
  end

  def admin?
    is? :admin
  end

  def recent_posts_for_user
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!

  def index
    @users = User.all.select('name, id, bio, email')
    render json: @users
  end

  def show
    @user = User.select('name, id, bio, email').find(params[:id])
    render json: @user
  end

  def create
    @user = User.new(user_params)

    if @user.save
      render json: @user, status: :created, location: @user
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  def update
    if @user.update(user_params)
      render json: @user
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.recent_posts_for_user
  end
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/views/users/index.html.erb
<h1>Display a list of all users</h1>
<div class="div-container">
<ul>
<% @users.each do |user| %>
<%= render partial: "shared/user", locals: { user: user }%>
<% end %>
</ul>
</div>

app/views/users/show.html.erb
<h1>Display a specific user</h1>
<div>
<ul>
<%= render "shared/user",  user: @user%>
</ul>
<div class = "bio-container">
<div class ="bio-wrapper">
<h5 class ="blog-title">Bio</h5>
<li  class = "blog-text" ><%= @user.bio%></li>
</div>

<%= link_to "Add post", new_user_post_path(@user.id), class: "add-cmt-btn", remote: true %>
</div>
<div >
<ul>
<%@posts.each do |post|%>
<div class = "show-li_elements">
<%= render partial: "shared/post", locals: { post: post }%>
<%= render partial: "shared/counters", locals: { post: post}%>
<div class = "interaction-btn">
<div class = "add-del-wrapper">
<%= link_to "Add a comment", new_user_post_comment_path(post.author, post), class: "add-cmt-btn", remote: true %>
<% if can? :destroy, post %>
   <%= button_to 'Delete post', user_post_path(post.author, post), class: "add-cmt-btn", method: :delete %>
<%end%>
</div>
<%=render 'shared/likes_form', post: post%>
</div> 
</div>
<% end %>
</ul>
</div>
<div class="btn-link">
<button class="btn-users">
<a  href="/users/<%= @user.id %>/posts">See all posts</a>
</button>
</div>
</div>