config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
root "users#index"

resources :users, only: [:index, :show] do
  resources :posts, only: [:index, :show, :new, :create, :destroy] do
    resources :comments, only: [:create, :new, :destroy] 
    resources :likes, only: [:create, :destroy] 

end
end

# API endpoints

namespace :api do
  namespace :v1 do
    resources :users, only: [:index, :create, :update, :destroy, :show] do
      resources :posts, only: [:index, :create, :update, :destroy, :show] do
        resources :comments, only: [:index, :show, :create]
        resources :likes, only: [:index, :show]
      end
    end
  end
end
end

app/views/shared/_comment.html.erb
        <div  class = "comment-section">
          <% post.comments.each do |comment| %>
            <li ><span class = "comment-author"><%= comment.author.name %>: </span> <%= comment.text %></li>
              <% if can? :destroy, comment %>
   <%= button_to 'Delete comment', user_post_comment_path(comment.author, post, comment ), class: "add-cmt-btn", method: :delete %>
        <%end %>
         <% end %>          
      </div>
          

app/views/shared/_comment_form.html.erb
<div class = "form-wrapper">
<%= form_with(model: @comments), url: user_post_comments_path, scope: :comment do |f| %>
<div>
  <%= f.label :comment %><br>
  <%= f.text_area :text, class: "form-text" %>
</div>

<div>
<%=f.submit class: "form-btn"%>
</div>

<% end %>

</div>

app/views/shared/_counters.html.erb
<span class = "show-post-counts">
<li>Comments: <%= post.comments_counter%></li>
<li>Likes: <%= post.likes_counter%></li>
</span>

app/views/shared/_likes_form.html.erb
 <div class ="likes-wrapper">
 <%= form_with(model: @likes), url: user_post_likes_path(post.author, post.id), scope: :like do |form| %>
    <%= form.submit 'Like', class: "form-btn"%>
<% end %>
</div>

app/views/shared/_post.html.erb
<li class ="blog-title">  <a href="/users/<%= @user.id %>/posts/<%= post.id %>"><%= post.title %></a></li>
<li class = "blog-text" ><%= post.text%></li>

app/views/shared/_post_form.html.erb
<%= form_with(model: [@post]), url:user_posts_path, local: true  do |f| %>
<div>
  <%= f.label :title%><br>
  <%= f.text_field :title,  class: "form-title" %>
</div>
<div>
  <%= f.label :text %><br>
  <%= f.text_area :text, class: "form-text" %>
</div>

<div>
<%=f.submit class: "form-btn"%>
</div>

<% end %>

app/views/shared/_user.html.erb
<div  class = "user-idx-div-container">
<span class = "img-box">
<img   class="img-form" src="<%= user.photo %>" alt="User Photo"> 
</span>
<span class = "li_elements">
 <li><%=link_to user.name, user_path(user)%></li>
 <li>Number of posts: <%= user.posts_counter%></li>
</span>
</div>